branches:
  only:
    - master
    - develop
language: python
cache: pip
notifications:
  email: false
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
install: pip install -r requirements.txt
# command to run tests
script: coverage run --rcfile=.coveragerc -m unittest discover
after_success: 
  - codeclimate-test-reporter --token $CC_TEST_REPORTER_ID
