branches:
  only:
    - master
    - develop
language: python
#cache: pip
notifications:
  email: false
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install: 
- pip install -r requirements.txt
- pip install mypy
# command to run tests
script: 
- coverage run --rcfile=.coveragerc -m unittest discover
- mypy polyhedral_analysis
after_success: 
  - codeclimate-test-reporter --token $CC_TEST_REPORTER_ID
